name: CI
on: [push]

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg -y

      - name: Set up Python
        run: uv python install 312

      - name: Install the project
        run: uv sync --dev

      - name: Run tests
        run: uv run pytest
  
  static_checks:
    name: Static checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg -y

      - name: Set up Python
        run: uv python install 312

      - name: Ruff check
        run: uvx ruff check
